GET /login
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer adsfasfdasf.adfs.afda;

###

POST /register
Content-Type: application/json
Host: localhost:8080

{
  "username": "liverbird",
  "password": "1234",
  "userClass": 2,
  "name": "donghun"
}

###

POST /login
Content-Type: application/json
Host: localhost:8080

{
  "username": "liverbird",
  "password": "1234"
}

###

POST /anonymity
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJyb2xlcyI6W10sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9sb2dpbiIsImV4cCI6MTY1ODE0MTgzNn0.Af9i8B9Z6-gJLgxyamcyTYNuDHYk_QYUnhbLS1e68JY

{
  "mailContent": "힘들어요"
}

###

GET /api/token/refresh
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvbG9naW4iLCJleHAiOjE2NTkwMDc3ODF9.o1PrOC6XSvf6iXSHSIDc98dmlP6bkTTW8Us1ODEd0dw