GET /login
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer adsfasfdasf.adfs.afda;

###

POST /register
Content-Type: application/json
Host: localhost:8080

{
  "username": "liverbird",
  "name": "donghun",
  "password": "1234",
  "userClass": 2
}

###

POST /api/login
Content-Type: application/json
Host: localhost:8080

{
  "username": "liverbird",
  "password": "1234"
}

###

POST /anonymity
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJhdWQiOiJST0xFX1VTRVIiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBpL2xvZ2luIiwiZXhwIjoxNjU5MjcxNzgzfQ.vaPmUZqDscYgSXH-R7_GHTOQZgu08u44-m4oazKr1-g

{
  "mailContent": "힘들어요"
}

###

GET /api/token/refresh
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBpL3Rva2VuL3JlZnJlc2giLCJleHAiOjE2NTk4NjgyMjh9.76tyGA1lyroU6aOLWDf7PwN9hyaYYV36NqYi-7z6ZU0

###

GET /api/token/save-refresh
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBpL2xvZ2luIiwiZXhwIjoxNjU5ODQ2MTUyfQ.LOAPBKB9YEq9FIPF7pmfPrQ3cKqGp_2A-QsRY_yOUv8

###

POST /api/logout
Content-Type: application/json
Host: localhost:8080

{
  "username": "liverbird"
}

###

GET /api/comments/getAllByPost/4
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsImV4cCI6MTY1OTI2OTIwMH0.OwPJ1-uoDShTdMG7dfqhMdSwMiEmI4U1H5HjarD5rRM

###

POST /api/comments/create
Content-Type: application/json
Host:localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsImV4cCI6MTY1OTI3MTQwNn0.TXA9fKfAxk3ywvS8AxxSe0iPr3fi9rrFBDo9woGFb3E

{
  "commentContent": "댓글3",
  "userId": 27,
  "postNo": 4,
  "topCommentNo": 0
}

###

PUT /comments/modify
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2xvZ2luIiwiZXhwIjoxNjU4OTIwMjU4fQ.i4ZIOpyYHAKod_Zc3MJpX-LOdSb4n8t0ElbecNb-CnU

{
  "commentNo": 3,
  "commentContent": "수정 댓글 1-2"
}

###

DELETE /api/comments/remove/11
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS9sb2dpbiIsImV4cCI6MTY1OTI3MTQwNn0.TXA9fKfAxk3ywvS8AxxSe0iPr3fi9rrFBDo9woGFb3E