GET /login
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer adsfasfdasf.adfs.afda;

###

POST /register
Content-Type: application/json
Host: localhost:8080

{
  "username": "liverbird",
  "name": "donghun",
  "password": "1234",
  "userClass": 2
}

###

POST /login
Content-Type: application/json
Host: localhost:8080

{
  "username": "liverbird",
  "password": "1234"
}

###

POST /anonymity
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2xvZ2luIiwiZXhwIjoxNjU4NDA2NDEzfQ.-VWlVcZrUgTGopi8G2FHohqjU6XJKauPg2tXpzIfQi0

{
  "mailContent": "힘들어요"
}

###

GET /api/token/refresh
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvbG9naW4iLCJleHAiOjE2NTk2MjYxNjZ9.M_70iAdV55PBgHhZy2VlMXFG0gZLJHBMJSLEW7R5fkM

###

GET /inputrefresh
Content-Type: application/json
Host: localhost:8080
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsaXZlcmJpcmQiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvbG9naW4iLCJleHAiOjE2NTk2MjYxNjZ9.M_70iAdV55PBgHhZy2VlMXFG0gZLJHBMJSLEW7R5fkM

###

POST /logout
Content-Type: application/json
Host: localhost:8080

{
  "username": "liverbird"
}

###
